/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.enmer.compi2.vista;

import com.enmer.compi2.projects.FileModel;
import com.enmer.compi2.projects.PackageModel;
import com.enmer.compi2.projects.ProjectModel;
import com.enmer.compi2.projects.ProjectXML;
import java.io.File;
import java.nio.file.Path;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author Admin
 */
public class IDERecaf extends javax.swing.JFrame {
    ProjectModel projectModel;
    

    /**
     * Creates new form IDE
     */
    public IDERecaf() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("IDE");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        treeProyecto = new javax.swing.JTree();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        newProjectButton = new javax.swing.JMenuItem();
        newFileButton = new javax.swing.JMenuItem();
        openProjectButton = new javax.swing.JMenuItem();
        openFileButton = new javax.swing.JMenuItem();
        saveButton = new javax.swing.JMenuItem();
        saveAsButton = new javax.swing.JMenuItem();
        closeProjectButton = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        compileButton = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        downloadButton = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(treeProyecto);

        jScrollPane2.setViewportView(jTextPane1);

        jLabel1.setText("CONSOLE");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        jMenu1.setText("Opciones");

        newProjectButton.setText("Nuevo Proyecto");
        newProjectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newProjectButtonActionPerformed(evt);
            }
        });
        jMenu1.add(newProjectButton);

        newFileButton.setText("Nuevo Archivo");
        jMenu1.add(newFileButton);

        openProjectButton.setText("Abrir Proyecto");
        openProjectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openProjectButtonActionPerformed(evt);
            }
        });
        jMenu1.add(openProjectButton);

        openFileButton.setText("Abrir Archivo");
        jMenu1.add(openFileButton);

        saveButton.setText("Guardar");
        jMenu1.add(saveButton);

        saveAsButton.setText("Guardar Como");
        jMenu1.add(saveAsButton);

        closeProjectButton.setText("Cerrar Proyecto");
        jMenu1.add(closeProjectButton);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Compilar");

        compileButton.setText("Codigo en Tres Direcciones");
        jMenu2.add(compileButton);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Descargar");

        downloadButton.setText("Codigo En Tres Direcciones");
        jMenu3.add(downloadButton);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1365, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newProjectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newProjectButtonActionPerformed
        // TODO add your handling code here:
        crearNuevoProyecto();
    }//GEN-LAST:event_newProjectButtonActionPerformed

    private void openProjectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openProjectButtonActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.setDialogTitle("Abrir project.xml");
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);

        int res = chooser.showOpenDialog(this);
        if (res != JFileChooser.APPROVE_OPTION) return;

        File xml = chooser.getSelectedFile();

        try {
            this.projectModel = ProjectXML.load(xml.toPath());
            cargarProyectoEnArbol();            
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "No se pudo abrir: " + e.getMessage());
        }
    }//GEN-LAST:event_openProjectButtonActionPerformed

    private void crearNuevoProyecto(){
        try {
            JFileChooser jfileChooser = new JFileChooser();
            jfileChooser.setDialogTitle("Seleccione la carpeta para el proyecto");
            jfileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
            jfileChooser.setAcceptAllFileFilterUsed(false);
            
            int res = jfileChooser.showSaveDialog(this);
            if (res != JFileChooser.APPROVE_OPTION) {
                return; 
            }

            File carpeta = jfileChooser.getSelectedFile();

            String nombre = javax.swing.JOptionPane.showInputDialog(
                    this,
                    "Nombre del proyecto:",
                    "ProyectoDecaf"
            );
            if (nombre == null || nombre.isBlank()) {
                return;
            }

            Path root = carpeta.toPath().resolve(nombre); 
            this.projectModel = ProjectXML.createNew(nombre, root);

            cargarProyectoEnArbol();
            
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(
                    this,
                    "No se pudo crear el proyecto: " + e.getMessage(),
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE
            );
        }
    }
    
    private void cargarProyectoEnArbol() {
        if (projectModel == null) return;

        DefaultMutableTreeNode rootNode =
                new DefaultMutableTreeNode(projectModel.getName());

        for (PackageModel pkg : projectModel.getPackages()) {
            DefaultMutableTreeNode pkgNode =
                    new DefaultMutableTreeNode(pkg.getName());

            for (FileModel fm : pkg.getFiles()) {
                DefaultMutableTreeNode fileNode =
                        new DefaultMutableTreeNode(fm.getName());
                pkgNode.add(fileNode);
            }

            rootNode.add(pkgNode);
        }

        DefaultTreeModel model = new DefaultTreeModel(rootNode);
        treeProyecto.setModel(model);
    }
            
            
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IDERecaf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IDERecaf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IDERecaf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IDERecaf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IDERecaf().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem closeProjectButton;
    private javax.swing.JMenuItem compileButton;
    private javax.swing.JMenuItem downloadButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JMenuItem newFileButton;
    private javax.swing.JMenuItem newProjectButton;
    private javax.swing.JMenuItem openFileButton;
    private javax.swing.JMenuItem openProjectButton;
    private javax.swing.JMenuItem saveAsButton;
    private javax.swing.JMenuItem saveButton;
    private javax.swing.JTree treeProyecto;
    // End of variables declaration//GEN-END:variables
}
